[package]
name = "KittenVM"
version = "0.1.0"
edition = "2021"
authors = ["Shirasawa"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.63"
tokio = "1.21.0"